name: "Setup Tech Stack"
description: "Sets up the required tech stack based on app configuration"

inputs:
  app-id:
    description: "Key of the app in config.json"
    required: true
  config-path:
    description: "Path to config.json"
    required: true
    default: ./config.json

outputs:
  directory:
    description: "The directory of the app"
    value: ${{ steps.config.outputs.directory }}

  type:
    description: "The type of the app"
    value: ${{ steps.config.outputs.type }}

  version:
    description: "The version"
    value: ${{ steps.config.outputs.version }}

  install-command:
    description: "Install command"
    value: ${{ steps.config.outputs.install_command }}

  test-command:
    description: "Test command"
    value: ${{ steps.config.outputs.test_command }}

  build-command:
    description: "Build command"
    value: ${{ steps.config.outputs.build_command }}

  lint:
    description: "Whether linting is enabled"
    value: ${{ steps.config.outputs.lint }}

  lint-path:
    description: "Optional linting subdirectory"
    value: ${{ steps.config.outputs.lint_path }}

runs:
  using: composite
  steps:
    #################################################################
    #             READ CONFIG (Backend + Frontend Safe)            #
    #################################################################
    - name: Read app config
      id: config
      shell: bash
      run: |
        CONFIG_PATH="${{ inputs.config-path }}"
        APP_ID="${{ inputs.app-id }}"

        if [ ! -f "$CONFIG_PATH" ]; then
          echo "❌ config.json not found at $CONFIG_PATH"
          exit 1
        fi

        APP=$(jq -c \
          --arg id "$APP_ID" \
          '.apps.backend[$id] // .apps.frontend[$id] // null' \
          "$CONFIG_PATH")

        if [[ "$APP" == "null" ]]; then
          echo "❌ ERROR: App ID '$APP_ID' not found in backend or frontend"
          exit 1
        fi

        safe_get() {
          echo "$APP" | jq -r --arg k "$1" \
            'if has($k) and .[$k] != null then .[$k] else "" end'
        }

        DIR=$(safe_get "directory")
        TYPE=$(safe_get "type")
        VERSION=$(safe_get "version")
        INSTALL=$(safe_get "install-command")
        TEST=$(safe_get "test-command")
        BUILD=$(safe_get "build-command")
        LINT=$(safe_get "lint")
        LINT_PATH=$(echo "$APP" | jq -c '."lint-path" // ""')

        if [ -z "$DIR" ]; then
          echo "❌ Missing 'directory' in config"
          exit 1
        fi

        echo "directory=$DIR"           >> $GITHUB_OUTPUT
        echo "type=$TYPE"               >> $GITHUB_OUTPUT
        echo "version=$VERSION"         >> $GITHUB_OUTPUT
        echo "install_command=$INSTALL" >> $GITHUB_OUTPUT
        echo "test_command=$TEST"       >> $GITHUB_OUTPUT
        echo "build_command=$BUILD"     >> $GITHUB_OUTPUT
        echo "lint=$LINT"               >> $GITHUB_OUTPUT
        echo "lint_path=$LINT_PATH"     >> $GITHUB_OUTPUT

    #################################################################
    #                      LANGUAGE SETUP                           #
    #################################################################
    - name: Setup Node.js
      if: ${{ steps.config.outputs.type == 'node' }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ steps.config.outputs.version }}

    - name: Setup Python
      if: ${{ steps.config.outputs.type == 'python' }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ steps.config.outputs.version }}

    - name: Setup Flutter
      if: ${{ steps.config.outputs.type == 'flutter' }}
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ steps.config.outputs.version }}

    - name: Setup Java
      if: ${{ steps.config.outputs.type == 'java' }}
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: ${{ steps.config.outputs.version }}

    - name: Setup Go
      if: ${{ steps.config.outputs.type == 'go' }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ steps.config.outputs.version }}

    #################################################################
    #                   INSTALL / TEST / BUILD                      #
    #################################################################
    - name: Install dependencies
      shell: bash
      working-directory: ${{ steps.config.outputs.directory }}
      run: ${{ steps.config.outputs.install_command }}

    - name: Run tests
      shell: bash
      working-directory: ${{ steps.config.outputs.directory }}
      run: ${{ steps.config.outputs.test_command }}

    - name: Build application
      shell: bash
      working-directory: ${{ steps.config.outputs.directory }}
      run: ${{ steps.config.outputs.build_command }}
