name: "Deploy Module to AWS S3"
description: "Deploys a frontend module using config.yaml + deployment-config.yaml"

inputs:
  app-type:
    required: true
  app-id:
    required: true

  config-path:
    required: true
    default: ./config.yaml

  aws-config-path:
    required: true
    default: ./deployment-config.yaml

  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true

runs:
  using: composite
  steps:

    ##################################################################
    #                    INSTALL yq (YAML parser)                    #
    ##################################################################
    - name: Install yq
      shell: bash
      run: |
        sudo wget -qO /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/bin/yq

    ##################################################################
    #              READ MODULE CONFIG (from YAML)                    #
    ##################################################################
    - name: Read module config
      id: cfg
      shell: bash
      run: |
        CFG="${{ inputs.config-path }}"
        APP_ID="${{ inputs.app-id }}"
        APP_TYPE="${{ inputs.app-type }}"

        # Extract from YAML: apps.<type>.<id>
        APP=$(yq -o=json ".apps.${APP_TYPE}.${APP_ID} // {}" "$CFG")

        if [[ "$APP" == "{}" ]]; then
          echo "❌ Module not found in YAML."
          exit 1
        fi

        safe() {
          echo "$APP" | yq -r ".$1 // \"\""
        }

        DIR=$(safe "directory")
        BUILD_CMD=$(safe "build-command")
        DEPLOY=$(safe "deploy")

        echo "directory=$DIR"   >> $GITHUB_OUTPUT
        echo "build=$BUILD_CMD" >> $GITHUB_OUTPUT
        echo "deploy=$DEPLOY"   >> $GITHUB_OUTPUT

    ##################################################################
    #          READ AWS HOSTING CONFIG (from YAML)                   #
    ##################################################################
    - name: Read AWS hosting config
      id: aws
      shell: bash
      run: |
        AWS_CFG="${{ inputs.aws-config-path }}"
        APP_ID="${{ inputs.app-id }}"
        APP_TYPE="${{ inputs.app-type }}"

        # Extract from YAML: <type>.<id>
        APP=$(yq -o=json ".${APP_TYPE}.${APP_ID} // {}" "$AWS_CFG")

        if [[ "$APP" == "{}" ]]; then
          echo "❌ AWS hosting info missing for module '$APP_ID'"
          exit 1
        fi

        BUCKET=$(echo "$APP" | yq -r '.bucket')
        REGION=$(echo "$APP" | yq -r '.region')

        echo "bucket=$BUCKET" >> $GITHUB_OUTPUT
        echo "region=$REGION" >> $GITHUB_OUTPUT

    ##################################################################
    #                         BUILD FRONTEND                         #
    ##################################################################
    - name: Build frontend
      if: ${{ steps.cfg.outputs.deploy == 'true' }}
      shell: bash
      working-directory: ${{ steps.cfg.outputs.directory }}
      run: |
        echo "🏗️ Building..."
        ${{ steps.cfg.outputs.build }}

    ##################################################################
    #                         AWS LOGIN                              #
    ##################################################################
    - name: Configure AWS
      if: ${{ steps.cfg.outputs.deploy == 'true' }}
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ steps.aws.outputs.region }}

    ##################################################################
    #                           DEPLOY                                #
    ##################################################################
    - name: Deploy to S3
      if: ${{ steps.cfg.outputs.deploy == 'true' }}
      shell: bash
      run: |
        aws s3 sync \
          ${{ steps.cfg.outputs.directory }}/build \
          s3://${{ steps.aws.outputs.bucket }} \
          --delete

        echo "✨ Deployment to S3 complete."
