name: "Deploy Module to AWS S3"
description: "Deploys a frontend module using config.json + deployment-config.yaml"

inputs:
  app-type:
    required: true
  app-id:
    required: true

  config-path:
    required: true
    default: ./config.json   # <-- JSON file

  aws-config-path:
    required: true
    default: ./frontend-config.yaml   # <-- YAML file

  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true

runs:
  using: composite
  steps:

    ##################################################################
    #                    INSTALL jq + yq                             #
    ##################################################################
    - name: Install jq + yq
      shell: bash
      run: |
        sudo apt-get update -y
        sudo apt-get install -y jq
        sudo wget -qO /usr/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/bin/yq

    ##################################################################
    #                  READ MODULE CONFIG (JSON)                     #
    ##################################################################
    - name: Read module config (JSON)
      id: cfg
      shell: bash
      run: |
        CFG="${{ inputs.config-path }}"
        APP_ID="${{ inputs.app-id }}"
        APP_TYPE="${{ inputs.app-type }}"

        # Extract JSON: .apps[type][id]
        APP=$(jq -c \
          --arg t "$APP_TYPE" \
          --arg id "$APP_ID" \
          '.apps[$t][$id] // null' "$CFG")

        if [[ "$APP" == "null" ]]; then
          echo "❌ Module not found in config.json"
          exit 1
        fi

        safe() {
          echo "$APP" | jq -r --arg k "$1" 'if has($k) then .[$k] else "" end'
        }

        DIR=$(safe "directory")
        BUILD_CMD=$(safe "build-command")
        DEPLOY=$(safe "deploy")

        echo "directory=$DIR"   >> $GITHUB_OUTPUT
        echo "build=$BUILD_CMD" >> $GITHUB_OUTPUT
        echo "deploy=$DEPLOY"   >> $GITHUB_OUTPUT

    ##################################################################
    #              READ AWS HOSTING CONFIG (YAML)                    #
    ##################################################################
    - name: Read AWS hosting config (YAML)
      id: aws
      shell: bash
      run: |
        AWS_CFG="${{ inputs.aws-config-path }}"
        APP_ID="${{ inputs.app-id }}"
        APP_TYPE="${{ inputs.app-type }}"

        # Extract YAML: <type>.<id>
        APP=$(yq -o=json ".${APP_TYPE}.${APP_ID} // {}" "$AWS_CFG")

        if [[ "$APP" == "{}" ]]; then
          echo "❌ AWS hosting info missing for '${APP_ID}'"
          exit 1
        fi

        BUCKET=$(echo "$APP" | yq -r '.s3_bucket // .bucket')
        REGION=$(echo "$APP" | yq -r '.s3_region // .region')

        echo "bucket=$BUCKET" >> $GITHUB_OUTPUT
        echo "region=$REGION" >> $GITHUB_OUTPUT

    ##################################################################
    #                         BUILD FRONTEND                         #
    ##################################################################
    - name: Build frontend
      if: ${{ steps.cfg.outputs.deploy == 'true' }}
      shell: bash
      working-directory: ${{ steps.cfg.outputs.directory }}
      run: |
        echo "🏗️ Building frontend..."
        ${{ steps.cfg.outputs.build }}

    ##################################################################
    #                           AWS LOGIN                            #
    ##################################################################
    - name: Configure AWS
      if: ${{ steps.cfg.outputs.deploy == 'true' }}
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ steps.aws.outputs.region }}

    ##################################################################
    #                           DEPLOY                                #
    ##################################################################
    - name: Deploy to S3
      if: ${{ steps.cfg.outputs.deploy == 'true' }}
      shell: bash
      run: |
        aws s3 sync \
          ${{ steps.cfg.outputs.directory }}/build \
          s3://${{ steps.aws.outputs.bucket }} \
          --delete

        echo "✨ Deployment completed to S3 bucket: ${{ steps.aws.outputs.bucket }}"
