name: 'Deploy to S3'
description: 'Deploy build artifacts to S3'

inputs:
  app-type:
    description: 'Type of application'
    required: true
  app-id:
    description: 'ID of the application'
    required: true
  config-path:
    description: 'Path to config.json'
    required: true
  #aws-access-key-id:
    description: 'AWS access key ID'
    required: true
  #aws-secret-access-key:
    description: 'AWS secret access key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        #aws-access-key-id: ${{ inputs.aws-access-key-id }}
        #aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: us-east-1  # Default region for SSM calls

    - name: Get S3 bucket from SSM
      id: ssm
      shell: bash
      run: |
        PREFIX="/${{ inputs.app-type }}/${{ inputs.app-id }}"
        
        # Get bucket name from SSM
        BUCKET_PARAM="${PREFIX}/bucket"
        BUCKET=$(aws ssm get-parameter \
          --name "$BUCKET_PARAM" \
          --query 'Parameter.Value' \
          --output text 2>/dev/null || echo "")
          
        if [ -z "$BUCKET" ]; then
          echo "::error::Could not find S3 bucket in SSM at $BUCKET_PARAM"
          exit 1
        fi
        
        # Get region from SSM or use default
        REGION_PARAM="${PREFIX}/region"
        REGION=$(aws ssm get-parameter \
          --name "$REGION_PARAM" \
          --query 'Parameter.Value' \
          --output text 2>/dev/null || echo "us-east-1")
          
        echo "bucket=$BUCKET" >> $GITHUB_OUTPUT
        echo "region=$REGION" >> $GITHUB_OUTPUT

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.app-type }}-${{ inputs.app-id }}
        path: ./deploy

    - name: Deploy to S3
      shell: bash
      run: |
        aws s3 sync \
          ./deploy \
          s3://${{ steps.config.outputs.bucket }} \
          --delete \
          --acl public-read \
          --cache-control "public, max-age=31536000, immutable"