name: "Deploy Module to AWS S3"
description: "Deploys a frontend module using config.json + aws.config.json"

inputs:
  app-type:
    required: true
  app-id:
    required: true

  config-path:
    required: true
    default: ./config.json

  aws-config-path:
    required: true
    default: ./deployment.config.json

  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true

runs:
  using: composite
  steps:
    ##################################################################
    #              READ MODULE CONFIG (build info)                   #
    ##################################################################
    - name: Read module config
      id: cfg
      shell: bash
      run: |
        CONFIG_PATH="${{ inputs.config-path }}"
        APP_ID="${{ inputs.app-id }}"
        APP_TYPE="${{ inputs.app-type }}"

        # Extract full module config
        APP=$(jq -c \
          --arg t "$APP_TYPE" \
          --arg id "$APP_ID" \
          '.apps[$t][$id] // null' \
          "$CONFIG_PATH")

        if [[ "$APP" == "null" ]]; then
          echo "❌ Module not found."
          exit 1
        fi

        safe() {
          echo "$APP" | jq -r --arg k "$1" 'if has($k) then .[$k] else "" end'
        }

        DIR=$(safe "directory")
        BUILD_CMD=$(safe "build-command")
        DEPLOY=$(safe "deploy")

        echo "directory=$DIR"       >> $GITHUB_OUTPUT
        echo "build=$BUILD_CMD"     >> $GITHUB_OUTPUT
        echo "deploy=$DEPLOY"       >> $GITHUB_OUTPUT

    ##################################################################
    #              READ AWS CONFIG (bucket + region)                 #
    ##################################################################
    - name: Read AWS hosting config
      id: aws
      shell: bash
      run: |
        AWS_CFG="${{ inputs.aws-config-path }}"
        APP_ID="${{ inputs.app-id }}"
        APP_TYPE="${{ inputs.app-type }}"

        AWS_ENTRY=$(jq -c \
          --arg t "$APP_TYPE" \
          --arg id "$APP_ID" \
          '.[$t][$id] // null' \
          "$AWS_CFG")

        if [[ "$AWS_ENTRY" == "null" ]]; then
          echo "❌ AWS hosting info missing for module '$APP_ID'"
          exit 1
        fi

        BUCKET=$(echo "$AWS_ENTRY" | jq -r '.bucket')
        REGION=$(echo "$AWS_ENTRY" | jq -r '.region')

        echo "bucket=$BUCKET" >> $GITHUB_OUTPUT
        echo "region=$REGION" >> $GITHUB_OUTPUT

    ##################################################################
    #                         BUILD FRONTEND                         #
    ##################################################################
    - name: Build frontend
      if: ${{ steps.cfg.outputs.deploy == 'true' }}
      shell: bash
      working-directory: ${{ steps.cfg.outputs.directory }}
      run: |
        echo "🏗️ Building..."
        ${{ steps.cfg.outputs.build }}

    ##################################################################
    #                         AWS LOGIN                              #
    ##################################################################
    - name: Configure AWS
      if: ${{ steps.cfg.outputs.deploy == 'true' }}
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ steps.aws.outputs.region }}

    ##################################################################
    #                           DEPLOY                                #
    ##################################################################
    - name: Deploy to S3
      if: ${{ steps.cfg.outputs.deploy == 'true' }}
      shell: bash
      run: |
        aws s3 sync \
          ${{ steps.cfg.outputs.directory }}/build \
          s3://${{ steps.aws.outputs.bucket }} \
          --delete

        echo "✨ Deployment to S3 complete."
