name: 'Build and Test'
description: 'Build and test application based on stack configuration'

inputs:
  app-type:
    description: 'Type of application (frontend/backend)'
    required: true
  app-id:
    description: 'ID of the application'
    required: true
  config-path:
    description: 'Path to config.json'
    required: true

outputs:
  stack:
    description: 'The stack type (node, python, java, etc.)'
  dir:
    description: 'The working directory for the application'
  install_cmd:
    description: 'The command to install dependencies'
  build_cmd:
    description: 'The command to build the application'
  test_cmd:
    description: 'The command to run tests'

runs:
  using: 'composite'
  steps:
    - name: Install jq
      shell: bash
      run: sudo apt-get install -y jq

    - name: Load config and setup
      id: setup
      shell: bash
      run: |
        # Load config
        CFG=$(jq -c --arg type "${{ inputs.app-type }}" --arg id "${{ inputs.app-id }}" \
          '.apps[$type][$id]' "${{ inputs.config-path }}")
        
        # Extract values
        STACK=$(echo "$CFG" | jq -r '.type')
        DIR=$(echo "$CFG" | jq -r '.directory')
        INSTALL_CMD=$(echo "$CFG" | jq -r '.["install-command"]')
        BUILD_CMD=$(echo "$CFG" | jq -r '.["build-command"]')
        TEST_CMD=$(echo "$CFG" | jq -r '.["test-command"] // "echo No tests configured"')
        
        # Output values
        echo "stack=$STACK" >> $GITHUB_OUTPUT
        echo "dir=$DIR" >> $GITHUB_OUTPUT
        echo "install_cmd=$INSTALL_CMD" >> $GITHUB_OUTPUT
        echo "build_cmd=$BUILD_CMD" >> $GITHUB_OUTPUT
        echo "test_cmd=$TEST_CMD" >> $GITHUB_OUTPUT

    # Rest of the steps remain the same...

    - name: Setup Node.js
      if: ${{ steps.setup.outputs.stack == 'node' }}
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Setup Python
      if: ${{ steps.setup.outputs.stack == 'python' }}
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Setup Java
      if: ${{ steps.setup.outputs.stack == 'java' || steps.setup.outputs.stack == 'gradle' }}
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ steps.setup.outputs.dir }}
      run: ${{ steps.setup.outputs.install_cmd }}

    - name: Run Tests
      shell: bash
      working-directory: ${{ steps.setup.outputs.dir }}
      run: ${{ steps.setup.outputs.test_cmd }}

    - name: Build
      shell: bash
      working-directory: ${{ steps.setup.outputs.dir }}
      run: ${{ steps.setup.outputs.build_cmd }}
      if: ${{ steps.setup.outputs.build_cmd != '' }}

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: frontend-${{ inputs.app-id }}
        path: ${{ steps.setup.outputs.dir }}/build
        if-no-files-found: warn
        retention-days: 1